workflows:
  my-workflow:
    name: Default Workflow
    labels:
      - QA
      - ${TENANT_NAME}
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Unit tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json
        test_report: test-results/flutter.json
      - name: Integration tests
        script: |
          mkdir -p test-results 
          flutter -d emulator-5554 test --machine > test-results/flutter.json integration_test 
          # for iOS use: -d iPhone
        test_report: test-results/flutter.json
    artifacts:
      - build/**/outputs/bundle/**/*.aab